name: "PR Title Linter"

on:
  pull_request:
    types:
      - opened
      - edited
      - synchronize

jobs:
  validate-title:
    name: Validate PR title
    runs-on: ubuntu-latest
    steps:
      - name: Check Semantic PR Title
        uses: amannn/action-semantic-pull-request@v5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          requireScope: false
